:linkcss:
:stylesdir: css
:stylesheet: mystyle.css
:twoinches: width='360'
:full-width: width='100%'
:three-quarters-width: width='75%'
:two-thirds-width: width='66%'
:half-width: width='50%'
:half-size:
:one-thirds-width: width='33%'
:one-quarters-width: width='25%'
:thumbnail: width='60'
:imagesdir: images
:sourcesdir: codes
:icons: font
:hide-uri-scheme!:
:figure-caption: 図
:example-caption: リスト
:table-caption: 表
:appendix-caption: 付録
:xrefstyle: short
:section-refsig:
:chapter-refsig:

= 実装

NOTE: この演習は、グループで実施します。


== 実装の心得


実装も内部設計同様、サブシステムごとに実施します（外部設計で、開発単位が異なるところでサブシステムに分割したのを思い出しましょう）。
また、実装方式には、システム分析の方式設計で決めたように、 `model_to_code` で演習した方式を使います。


== 【準備】実装用のワークスペースを用意する

ワークスペースは Assignment として提供します。
このリポジトリは、実装用のワークスペースとしても使えるような構成にしてあります。
実装用ワークスペースは、  `sdk/workspace` の並びに、 `sdk/implements` （実際にはacceptしたとにできるリポジトリ名）として配置します。

NOTE: この配置方法で配置した場合、ワークスペースであると同時にリポジトリにもなるので、開発作業とコミットやプッシュも同じディレクトリで実施できるようになります。コミットのためにいちいちコピーしなくても済む

.実装の準備
. 実装用のグループ用Assignment（ `implements` ）を受け取る
. 受け取ったAssignmentのリポジトリを、 `sdk/workspace` の並びに移動する
** `sdk/implements` （実際にはacceptしたリポジトリ名）のようになる


[source,shell]
----
sdk
├── implements 実際はアクセプトしたときのリポジトリ名
│   ├── images
│   ├── park_ride
│   ├── sample04
│   └── util
├── samplesなど、ほかのディレクトリ
└── workspace
     ├── helloev3
     └── などなど
----


配置できたら、 `sample04` がビルドできるか確認しましょう（ `$` はターミナルのシェルのプロンプト）。

[source,shell]
----
$ make app=sample04
rm -rf /Users/kuboaki/Documents/ev3rt-mac/ev3rt-1.1-release/hrp3/sdk/implements/.././OBJ/
Generating Makefile from ../common/Makefile.app.
rm -f cfg1_out cfg1_out.o cfg1_out.c cfg1_out.syms cfg1_out.srec module_cfg.h module_cfg.c \#* *~ *.o
  CFG[1]  module_cfg.h

（略）

  LD      app
$ ls -l app
-rw-r--r-- 1 kuboaki 99576 10 16 15:05 app
----

== 【演習】内部設計に合わせた構造を用意する

Assignmentの `park_ride` は、配布時点では `sample04` と同じ内容ににしてあります。
ここからスタートして、自分たちの内部設計に合うように、実装方式に従って実装します。

=== 内部設計のパッケージに合わせてディレクトリを作る

実装においては、 `park_ride` ディレクトリの中身を書き換えていきます。
すでに別の場所に作成中のコードが有る場合には、そこから持ってきます。

内部設計のクラス図でパッケージに分割している場合には、プログラムもパッケージに分割します。

.  `park_ride` ディレクトリの中に、各パッケージ名と同じ名前のディレクトリを作る
** 例） クラス図に `app`  パッケージがあるなら、  `park_ride` ディレクトリの中に `app` ディレクトリを作る
** EV3RT用のライブラリは、自分たちでは使わない（外部にあるライブラリを参照する）ので、ディレクトリは作成しない
** `Makefile.inc` を編集して、追加したディレクトリをビルド対象に追加する

.`Makefile.inc` を更新した
[source,makefile]
----
file_path := $(dir $(lastword $(MAKEFILE_LIST))) # <1>

SRCLANG := c

APPL_ASMOBJS :=
ifdef USE_CXX
	APPL_CXXOBJS +=
	APPL_COBJS += util.o # <2>
else
	APPL_COBJS += util.o # <2>
endif

APPL_DIRS += $(mkfile_path)app \ # <3>
	$(mkfile_path)/../util
INCLUDES += \
	-I$(mkfile_path)app \  # <4>
	-I$(mkfile_path)/../util
----
<1> ビルド対象のディレクトリを `file_path` で参照する
<2> `util` ディレクトリにある関数を使うためにオブジェクトを追加してある
<3> ビルド対象のディレクトリ `app` を `APPL_DIRS` に追加した
<4> 参照するヘッダファイルがあるディレクトリ `app` を `INCLUDES` に追加した


他にもパッケージがあれば、同じようにして追加します。


=== パッケージにファイルを追加する

追加したパッケージに含まれるクラスの `.c` ファイルと `.h` ファイルを、パッケージに対応して追加したディレクトリに作成します。
ファイルを追加したあと、最低限のコードを書いたところで、ビルドできるか確認します。
一度にすべてのパッケージやクラスに手を付けず、1つずつ確認しながら追加していきます。

==== 主役となるクラスを追加する

たとえば、サブシステムの中にパッケージ `app` があって、そのに主役となるクラス「 `auto_ride` 」があったとします。

. パッケージ `app` に対応したディレクトリ `app` がまだないなら作成する
. 役のクラスが「 `auto_ride` 」クラスなら、 `auto_ride.c` と `auto_ride.h` を追加する

.`auto_ride.c` と `auto_ride.h` を追加した
[source,shell]
----
park_ride
├── Makefile.inc
├── app
│   ├── auto_ride.c
│   └── auto_ride.h
├── app.c
├── app.cfg
└── app.h
----

==== 主役となるクラスのファイルに最初のコードを書く

主役となるクラスの `.h` ファイルの最初のバージョンを作成します。

.`auto_ride.h`  の例
[source,c]
----
#ifndef AUTO_RIDE_H_  // <1>
#define AUTO_RIDE_H_  // <2>

#include "app.h" // <3>
#include "util.h" // <4>

extern void auto_ride_xxxx(void); // <5>

#endif // AUTO_RIDE_H_ // <6>
----
<1> 多重宣言を避けるためのインクルードガードの始まり
<2> インクルードガード用のマクロ定数の定義
<3> OSやセンサーやモーターの API の宣言や、その他の定義をしている `app.h` をインクルードしておく
<4> メッセージ表示などに使うユーティリティ関数の宣言をインクルードした
<5> 主役となるクラスのステートマシン図を担当する操作にあたる関数の外部参照宣言
<6> 多重宣言を避けるためのインクルードガードの終わり

主役となるクラスの `.c` ファイルの最初のバージョンを作成します。

.`auto_ride.c`  の例
[source,c]
----
#include "auto_ride.h" // <1>

void auto_ride_config(void) { // <2>
  // 中身はまだ書かない
}

void auto_ride_xxxx(void) { // <3>
  // 中身はまだ書かない
}
----
<1> 自分のクラスの `.h` ファイルをインクルードした
<2> 主役となるクラスのデバイスのコンフィギュレーションを担当する関数を追加した
<3> 主役となるクラスのステートマシン図を担当する操作にあたる関数を定義した


==== トップレベルの関数を修正する

サブシステムの主役の関数が作成できましたので、これを呼び出すように `app.c` を編集します。

.`app.c` ,  パッケージに `auto_ride` クラスがある例
[source,c]
----
#include "app.h"
#include "auto_ride.h" // <1>

void main_task(intptr_t unused) {
  auto_ride_xxxx(); // <2>
  ext_tsk();
}
----
<1> パッケージに含まれているクラスのヘッダファイルをインクルードした
<2> 主役となるクラスのステートマシン図を担当する関数の呼び出し

`app.h` も、主役の関数の外部参照宣言などを追加しておきます。

.`app.h` ,  パッケージに `auto_ride` クラスがある場合
[source,c]
----
#ifdef __cplusplus
extern "C" {
#endif

#include "stdbool.h" // <1>
#include "ev3api.h"

#define MAIN_PRIORITY    TMIN_APP_TPRI + 1

#ifndef STACK_SIZE
#define STACK_SIZE      4096
#endif /* STACK_SIZE */

#ifndef TOPPERS_MACRO_ONLY

extern void main_task(intptr_t exinf); // <2>

#endif /* TOPPERS_MACRO_ONLY */

#ifdef __cplusplus
}
#endif
----
<1> `bool` 型を使いたい場合にはインクルードしておく
<2> メインタスク用の関数の外部参照宣言を追加した


==== `app.cfg` ファイルを作成する

ビルドに必要なタスクや周期ハンドラを定義するために、コンフィギュレーションファイルを作成します（既にある場合には、修正します）。

.`app.cfg` を更新する
[source,c]
----
INCLUDE("app_common.cfg");

#include "app.h"

DOMAIN(TDOM_APP) {
  CRE_TSK( MAIN_TASK, { TA_NULL,  0, main_task,   MAIN_PRIORITY,   STACK_SIZE, NULL } ); // <1>
  CRE_CYC(CYC0, { TA_STA, { TNFY_ACTTSK, MAIN_TASK }, 50U * 1000, 1U *1000 }); // <2>
}

ATT_MOD("app.o");
ATT_MOD("util.o");  # <3>
ATT_MOD("auto_ride.o");  # <4>
----
<1>  `main_task` というC言語の関数をタスク `MAIN_TASK` の実態として使うことを宣言
<2> OSが起動して 1ms 後から、周期 50ms で `MAIN_TASK` を起動することを宣言
<3> `util.o` を追加した
<4> `auto_ride.o` を追加した

==== `Makefile.inc` ファイルを更新する

追加したクラスのオブジェクトをリンク対象にするために追加します。

.`Makefile.inc` を更新した
[source,makefile]
----
file_path := $(dir $(lastword $(MAKEFILE_LIST)))

SRCLANG := c

APPL_ASMOBJS :=
ifdef USE_CXX
	APPL_CXXOBJS +=
	APPL_COBJS += util.o auto_ride.o // <1>
else
	APPL_COBJS += util.o auto_ride.o // <2>
endif

APPL_DIRS += $(mkfile_path)app \
	$(mkfile_path)/../util
INCLUDES += \
	-I$(mkfile_path)app \
	-I$(mkfile_path)/../util
----
<1> こちらはC++で使うcのオブジェクト用なので、C++プログラムを書いていないなら更新しなくてもよい
<2> `auto_ride` のオブジェクトをリンク対象として追加した

=== ビルドしてみる

ここまでの修正がうまくいっているか確認するために、一度ビルドしてみましょう。

[source,shell]
----
$ pwd
`implements` をcloneしたディレクトリ
$ make app=park_ride
----

まだ、中身を作っていませんから、動かしても何も起きませんが、エラーがあれば対処しておきます。


=== 保存してコミットする

ここまでできたら、いったんコミットしておきましょう。
他の人作業を引き継ぐなら、プッシュして、次の担当にプルしてもらいましょう。


== 【演習】初期化処理を追加する

処理の最初に必要なコードを追加します。

=== 状態定数、状態変数を追加する

作成しようとしているクラスの内部設計のステートマシン図を参照して、`enum` を使って「状態の定数」を追加します。
また、現在の状態を覚えておく「状態変数」も定義します。

.`auto_ride.c`, `auto_ride` クラスが主役のクラスの例
[source,c]
----
#include "auto_ride.h" // <1>

typedef enum { // <1>
  AR_INIT, // <2>
  AR_WAIT_FOR_XXXX, AR_YYYY, AR_ZZZZ, // ...
} auto_ride_state;
auto_ride_state ar_state = AR_INIT; // <3>

void auto_ride_config(void) {
  // 中身はまだ書かない
}

void auto_ride_xxxx(void) {
  // 中身はまだ書かない
}
----
<1> 状態定数に使う列挙子の宣言の始まり
<2> 状態定数の定義。`AR` は `auto_ride` のプレフィクス（前置詞）として使っている
<3> 状態変数の定義。最初の状態で初期化しておく


=== ステートマシン図の処理の初期化部分を追加する

内部設計のステートマシン図を参照しながら、最初の状態の処理を追加します。
最初に追加するのは、ステートマシン図の処理の最初の部分です。
初期化処理については、状態を設けて明示的に処理として描いている場合もあれば、状態や処理を描いていない場合もあるでしょう。
状態を割り当てていない場合であっても、初期化には1つの状態定数を割り当てて、その中で関連するクラスの初期化を処理します。

.`auto_ride.c`, `auto_ride` クラスが `unit_a` クラスを使っている例
[source,c]
----
#include "auto_ride.h"

typedef enum {
  AR_INIT,
  AR_WAIT_FOR_XXXX, AR_YYYY, AR_ZZZZ, // ...
} auto_ride_state;
auto_ride_state ar_state = AR_INIT;

void auto_ride_config(void) {
  // 中身はまだ書かない
}

void auto_ride_xxxx(void) {
  num_f(ar_state, 2); // <1>
  switch(ar_state) { // <2>
  case AR_INIT: // <3>
    auto_ride_config(); // <4>
    break;
  default:
    break;
  }
}
----
<1> 状態番号を表示するためにユーティリティ関数を使った
<2> 実装方式に従って、状態定数によって分岐する switch 文を使う
<3> 初期処理用の状態として `AR_INIT` を使うことにした
<4> 初期化処理を記載した関数 `auto_ride_config` を呼び出した

=== ビルドしてみる

ここまでの修正がうまくいっているか確認するために、一度ビルドしてみましょう。

[source,shell]
----
$ pwd
`implements` をcloneしたディレクトリ
$ make app=park_ride
----

まだ、中身を作っていませんから、動かしても何も起きませんが、エラーがあれば対処しておきます。


=== 保存してコミットする

ここまでできたら、いったんコミットしておきましょう。
他の人作業を引き継ぐなら、プッシュして、次の担当にプルしてもらいましょう。


=== 状態遷移を追加する

こんどは、次の状態への遷移と、遷移先の状態のアクションを追加します。
`auto_ride` クラスの例では、状態 `AR_INIT`  からは状態 `AR_WAIT_FOR_XXXX` へ遷移し、状態 `AR_WAIT_FOR_XXXX` からは、観光客が乗車すると、状態 `AR_YYYY` へ遷移するものとします。

.`auto_ride.c`, `auto_ride` クラスが `unit_a` クラスを使っている例
[source,c]
----
#include "auto_ride.h"

typedef enum {
  AR_INIT,
  AR_WAIT_FOR_XXXX, AR_YYYY, AR_ZZZZ, // ...
} auto_ride_state;
auto_ride_state ar_state = AR_INIT;

void auto_ride_config(void) {
  unit_a_config(); // <1>
}

void auto_ride_xxxx(void) {
  num_f(ar_state, 2);
  switch(ar_state) {
  case AR_INIT:
    auto_ride_config();
    ar_state = AR_WAIT_FOR_XXXX; // <2>
    break;
  case AR_WAIT_FOR_XXXX:
    if(unit_a_is_seated()) { // <3>
      ar_state = AR_YYYY;
    }
    break;
  case AR_YYYY:
    unit_a_do_act(); // <4>
    break;
  default:
    break;
  }
}
----
<1> 関連しているクラス unit_a の初期化処理の呼び出し
<2> 次の状態への遷移
<3> イベントの発生をポーリングによって監視している（状態が変わっていたら次の状態へ遷移する）
<4> 状態 `AR_YYYY` の doアクティビティのアクションとして `unit_a_do_act` を追加した


=== さらに状態とアクションを追加する

状態 `AR_INIT` のアクション `auto_ride_config`  では、`unit_a_config` が呼び出されています。
そして、状態 `AR_WAIT_FOR_XXXX` のイベント発生のチェックでは、 `unit_a_is_seated` を使っています。
これらのことと実装方式のによって、実装のためには、unitパッケージに対応した `unit` ディレクトリを追加し、そこに `unit_a.h` と `unit_a.c` を作成することになるのがわかります。

.`unit_a.h` と `unit_a.c` を追加した
[source,shell]
----
park_ride
├── Makefile.inc
├── app
│   ├── auto_ride.c
│   └── auto_ride.h
├── unit # <1>
│   ├── unit_a.c # <2>
│   └── unit_a.h # <2>
├── app.c
├── app.cfg
└── app.h
----
<1> `unit` ディレクトリを追加した
<2> `unit_a.h` と `unit_a.c` を追加した

ファイルが追加できたら、ファイルを編集します。

. 先に、`app.cfg` と `Makefile.inc` には、`unit_a.o` を追加しておきます。
. `unit_a.h` にインクルードガード、`util.h` のインクルード、関数 `unit_a_is_seated` の外部参照宣言を書く（この関数の戻り値の型が `bool` になることに注意）。
. `unit_a.c` では、 `unit.h` をインクルードし、 `auto_ride_config` 、`unit_a_is_seated` 、  `unit_a_do_act` を作成します。
** 関数の中身は、ビルドできることを確認してから作成します。

追加した2つのファイルに、外部参照宣言や中身が空の関数を書いたところで、一度ビルドしてみましょう。


=== config関数に初期処理を移す

これまでのサンプルでは、センサーやモーターは、`main_task` の冒頭にまとめてありました。
これを、それぞれのユニットの `config` 関数へ移します。

. `unit_a.c` の冒頭に、このユニットで使うセンサー（またはモーター）の変数を定義する
. `unit_a_config` 関数のなかで、このユニットで使うセンサー（またはモーター）の `config` 関数を呼び出して初期化する
. `unit_a_XXXX` 関数の状態 `AR_INIT` の処理のなかで、`unit_a_config` を呼び出す


=== アクションの中身を追加して動作を確認する

関数  `auto_ride_config` 、`unit_a_is_seated` 、  `unit_a_do_act` の中身を作成します。

中身ができたら、もう一度ビルドしてみます。

ビルドできたら、動作を確認しましょう。


=== 動作が確認できたらコミットする

ここまでできたら、いったんコミットしておきましょう。
他の人作業を引き継ぐなら、プッシュして、次の担当にプルしてもらいましょう。

=== すべての状態とアクションを追加する

残りの状態、状態遷移についても、必要なクラスやアクションを追加しながら、編集します。

. 1つの状態を追加する程度について、空の関数の追加が済んだら、ビルドする
. 追加した状態や状態遷移に使う関数の中身を作成し、ビルドする
. 動作を確認する

すべての状態とアクションを追加するまで、段階的に編集してはビルドする作業を繰り返します。


== 実装のまとめ

* サブシステムごとに、内部設計のクラス図とステートマシン図を参照しながら、実装方式に従って実装した
* 一度に実装せず、1段階ずつ（1状態あるいは1遷移ずつ）実装しては、ビルドできること、実行できることを確認した
* 実装の途中で、必要なクラスやアクションを追加するために、パッケージやクラスに対応するファイルを追加した
